on:
  # push:
  workflow_dispatch:
    inputs:
      input_file:


jobs:

  custom:
    runs-on: ubuntu-latest


    steps:

    - uses: li1ht2ay-3es/gi1-ac2io3s@checkout-repo
      with:
        token: ${{ secrets.token }}
        auto: true


    - shell: bash
      run: |
        sudo apt-get install \
          libboost-all-dev \
          libmpg123-dev


    - uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ matrix.arch }}


    - shell: bash
      run: |
        merge () {
          echo "<<< ===  merging  $1  === >>>";
          if [[ -z "$2" ]]; then
            git merge origin/$1 || { git diff --diff-filter=U; exit 1; }
          else
            git merge origin/$1 || { git diff --diff-filter=U; git merge --abort; git merge -X $2 origin/$1; }
          fi
          echo "";
        }



    - shell: bash
      env:
        CC: ccache gcc
        CXX: ccache g++
      run: |
        make


    - shell: bash
      if: inputs.input_file != ''
      run: |
        ./projectorrays decompile ${{ inputs.input_file }} --dump-scripts --dump-chunks --dump-json
        # ls -a


    - uses: actions/upload-artifact@main
      with:
        path: |
          *.bin
          *.json
          *.ls
          *.lasm
          *.dir
          *.cst
