on:
  push:
  workflow_dispatch:


jobs:

  custom:
    strategy:
      matrix:
        arch: [x86, x64]
      fail-fast: false


    runs-on: ubuntu-latest


    steps:

    - uses: li1ht2ay-3es/gi1-ac2io3s@checkout-repo
      with:
        token: ${{ secrets.token }}
        auto: true


    - uses: li1ht2ay-3es/gi1-ac2io3s@mingw-install
      with:
        arch: ${{ matrix.arch }}

    - run: |
        install: >-
          mingw-w64-x86_64-zlib
          mingw-w64-x86_64-boost
          mingw-w64-x86_64-mpg123
          # mingw-w64-x86_64-toolchain
          # vim

    - uses: hendrikmuhs/ccache-action@main
      with:
        key: ${{ matrix.arch }}


    - shell: bash
      run: |
        merge () {
          echo "<<< ===  merging  $1  === >>>";
          if [[ -z "$2" ]]; then
            git merge origin/$1 || { git diff --diff-filter=U; exit 1; }
          else
            git merge origin/$1 || { git diff --diff-filter=U; git merge --abort; git merge -X $2 origin/$1; }
          fi
          echo "";
        }



    - shell: bash
      env:
        CC: ccache ${{ env.MINGW_CC }}
        CXX: ccache ${{ env.MINGW_CXX }}
      run: |
        make



    - uses: actions/upload-artifact@main
      with:
        name: projectorrays_${{ matrix.arch }}
        path: ${{ github.workspace }}/**.exe
