on:
  push:
  workflow_dispatch:
    inputs:
      file:


jobs:

  build_windows:
    strategy:
      matrix:
        arch: [x86, x64]
      fail-fast: false


    runs-on: ubuntu-latest


    steps:

    - uses: li1ht2ay-3es/pr1je2to3ra4s@build
      with:
        arch: ${{ matrix.arch }}
        input_file: ${{ matrix.file }}

        token: ${{ secrets.token }}
