on:
  push:
  workflow_dispatch:


jobs:

  build_windows:
    strategy:
      matrix:
        arch: [x86, x64]
      fail-fast: false


    runs-on: windows-latest


    steps:

    - uses: li1ht2ay-3es/pr1je2to3ra4s@build
      with:
        branch: custom
        arch: ${{ matrix.arch }}

        token: ${{ secrets.token }}
